image:
  repository: ghcr.io/learning-mprb/hello-world-rails
  tag: latest
  pullPolicy: Always
imagePullSecrets:
  - name: ghcr-secret
  
replicaCount: 2

service:
  port: 80
  targetPort: 3000

ingress:
  host: localhost
